name: CI Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi --no-root

    - name: Run formatter check (Black)
      run: |
        black --check .

    - name: Run lint (Flake8)
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest

    - name: Run pipeline
      run: |
        python -m src.data.pipeline --input data/raw/sales_sample.csv --min-total 100